"use client";

import { FormEvent, useState } from "react";
import { Modal } from "@/components/Modal";
import { Data, idOf } from "@/lib/types";

export function PlatformAdminPage({ organisations, libraries, mutate }: { organisations: Data[]; libraries: Data[]; mutate: (path: string, method: string, data?: Data) => Promise<void> }) {
  const [showForm, setShowForm] = useState(false);
  const [showLibraryForm, setShowLibraryForm] = useState(false);
  return <div className="dashboard-body"><div className="dashboard-intro"><span className="login-overline">ESPACE PROPRIÉTAIRE</span><h2>Administration de la plateforme</h2><p>Créez les espaces clients et suivez leurs abonnements.</p></div><div className="maquette-stats"><div className="metric-card"><span>Organisations</span><strong>{organisations.length}</strong><small>clients enregistrés</small></div><div className="metric-card"><span>Bibliothèques</span><strong>{libraries.length}</strong><small>espaces créés pour les clients</small></div></div><section className="resource-table"><div className="panel-title-row admin-table-heading"><div><span className="panel-kicker">Clients</span><h3>Organisations et abonnements</h3></div><button className="orange-button" onClick={() => setShowForm(true)}>＋ Nouvelle organisation</button></div><table><thead><tr><th>Nom</th><th>Email</th><th>Abonnement</th><th>Expiration</th><th>Statut</th></tr></thead><tbody>{organisations.map((organisation) => <tr key={idOf(organisation)}><td><strong>{String(organisation.nom)}</strong></td><td>{String(organisation.email || "-")}</td><td><select value={String(organisation.abonnement_plan || "standard")} onChange={(event) => mutate(`/api/organisation/admin/${idOf(organisation)}/`, "PATCH", { abonnement_plan: event.target.value })}><option value="standard">Standard</option><option value="premium">Premium</option><option value="enterprise">Enterprise</option></select></td><td>{String(organisation.abonnement_fin || "Sans échéance")}</td><td><select value={String(organisation.abonnement_statut || "trial")} onChange={(event) => mutate(`/api/organisation/admin/${idOf(organisation)}/`, "PATCH", { abonnement_statut: event.target.value })}><option value="trial">Essai</option><option value="active">Active</option><option value="suspended">Suspendue</option><option value="expired">Expirée</option></select></td></tr>)}</tbody></table></section><section className="resource-table admin-library-table"><div className="panel-title-row admin-table-heading"><div><span className="panel-kicker">Espaces clients</span><h3>Bibliothèques</h3></div><button className="orange-button" onClick={() => setShowLibraryForm(true)}>＋ Nouvelle bibliothèque</button></div><table><thead><tr><th>Nom</th><th>Slug</th><th>Organisation</th><th>Statut</th></tr></thead><tbody>{libraries.map((library) => <tr key={idOf(library)}><td><strong>{String(library.nom)}</strong></td><td>{String(library.slug)}</td><td>{String(library.organisation)}</td><td><span className="status-pill disponible">Active</span></td></tr>)}</tbody></table></section>{showForm && <Modal title="Créer une organisation" onClose={() => setShowForm(false)}><OrganisationForm mutate={mutate} onClose={() => setShowForm(false)} /></Modal>}{showLibraryForm && <Modal title="Créer une bibliothèque client" onClose={() => setShowLibraryForm(false)}><LibraryForm organisations={organisations} mutate={mutate} onClose={() => setShowLibraryForm(false)} /></Modal>}</div>;
}

function OrganisationForm({ mutate, onClose }: { mutate: (path: string, method: string, data?: Data) => Promise<void>; onClose: () => void }) {
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); await mutate("/api/organisation/admin/create/", "POST", Object.fromEntries(new FormData(event.currentTarget))); onClose(); }
  return <form className="modal-form" onSubmit={submit}><div className="grid"><label>Nom<input name="nom" required /></label><label>Slug<input name="slug" required pattern="[a-z0-9-]+" /></label><label>Email<input name="email" type="email" required /></label><label>Téléphone<input name="telephone" required /></label></div><label>Adresse<textarea name="adresse" rows={3} /></label><div className="modal-actions"><button type="button" className="cancel-button" onClick={onClose}>Annuler</button><button className="modal-submit" type="submit">Créer</button></div></form>;
}

function LibraryForm({ organisations, mutate, onClose }: { organisations: Data[]; mutate: (path: string, method: string, data?: Data) => Promise<void>; onClose: () => void }) {
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); await mutate("/api/bibliotheque/admin/", "POST", Object.fromEntries(new FormData(event.currentTarget))); onClose(); }
  return <form className="modal-form" onSubmit={submit}><div className="grid"><label>Organisation<select name="organisation" required>{organisations.map((organisation) => <option key={idOf(organisation)} value={idOf(organisation)}>{String(organisation.nom)}</option>)}</select></label><label>Nom<input name="nom" required /></label><label>Slug<input name="slug" required pattern="[a-z0-9-]+" /></label><label>Email<input name="email" type="email" required /></label><label>Téléphone<input name="telephone" required /></label></div><label>Adresse<textarea name="adresse" rows={3} required /></label><div className="modal-actions"><button type="button" className="cancel-button" onClick={onClose}>Annuler</button><button className="modal-submit" type="submit">Créer</button></div></form>;
}
